# Base de datos
spring.data.mongodb.uri=mongodb://mongo:27017/productividadplus

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# Correo SMTP Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu_correo@gmail.com
spring.mail.password=tu_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Sesión
server.servlet.session.timeout=30m

# Aplicación
spring.application.name=ProductividadPlus
app.mail.from=ProductividadPlus <tu_correo@gmail.com>
app.base-url=http://localhost:8080
